services:
  mysql:
    image: mysql:9.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql

